#!/bin/sh
PANDOC="pandoc -fmarkdown_github+pandoc_title_block -thtml5 -s --email-obfuscation=references"
POSTS=
if [ $# -eq 0 ]
then
	POSTS=`$PANDOC --template post.template.html`$POSTS
else
	for f in $*; do POSTS=`$PANDOC --template post.template.html "$f"`$POSTS; done
fi
echo "$POSTS" | $PANDOC --template template.html
